eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name:  trend-trading-backtest-service
  zipkin:
    base-url: http://localhost:9411

#用于开启 feign 模式的断路器
feign.hystrix.enabled: true